apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-gitops
spec:
  selector:
    matchLabels:
      app: fc-gitops
  template:
    metadata:
      labels:
        app: fc-gitops
    spec:
      containers:
        - name: fc-gitops
          image: fc-gitops:latest
          ports:
            - containerPort: 3000
